baseURL = "https://xfdzcoder.github.io/home"
languageCode = "zh-cn"
title = "XFDZ's blog"
theme = "github-style"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "XFDZ"
  description = "A coder."
  github = "xfdzcoder"
  facebook = ""
  twitter = ""
  linkedin = ""
  instagram = ""
  tumblr = ""
  email = "xfdzcoder@gmail.com"
  url = ""
  keywords = "blog, google analytics"
  rss = false
  lastmod = true
  favicon = "/images/github-mark.png"
  avatar = "https://cdn.jsdelivr.net/gh/zrgzs/images@main/images/2024%2F07%2F18%2F10-06-57-0a54e79d9d15bff3ff45ed23c3ca3725-F81SJ7MxrpkPV1DKwIHIhBQ5H2MXFq7E-e4dab1.jpg"
  headerIcon = "/images/github-mark-white.png"
  location = "China"
  userStatusEmoji = "ğŸ˜€"
  enableGitalk = false

  [params.gitalk]
    clientID = "Your client ID" # Your client ID
    clientSecret = "Your client secret" # Your client secret
    repo = "LuvSia" # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
    owner = "ventusoon" # æ‚¨çš„GitHub ID
    admin = "ventusoon" # æ‚¨çš„GitHub ID
    id = "location.pathname" # æ–‡ç« é¡µé¢çš„é“¾æ¥åœ°å€å°±æ˜¯ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # è®¾ç½®ä¸ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # å¯ä»¥è‡ªè¡Œæ·»åŠ åå‘ä»£ç†
#  [[params.links]]
#    title = "Link"
#    href = "https://github.com/xfdzcoder"
#  [[params.links]]
#    title = "Link2"
#    href = "https://meik2333.com"
#    icon = "https://meik2333.com/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
  [services.googleAnalytics]
    ID = "UA-123456-789"
